# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Omnom


on: [push,  pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub Pull Request context
      env:
        GITHUB_PR_CONTEXT: ${{ toJSON(github.event.pull_request) }}
      run: echo "$GITHUB_PR_CONTEXT"
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Merge PR Branches
      if: github.event_name == 'pull_request'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout ${{ github.event.pull_request.head.ref }}
        git pull
        git checkout ${{ github.event.pull_request.base.ref }}
        git pull
        git merge ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
